#! /bin/bash

# Linux and Darwin/BSD have different ways to get color
# in `ls`
if [[ $platform == 'linux' ]]; then
   alias ls='ls --color=auto'
elif [[ $platform == 'darwin' ]]; then
   alias ls='ls -G'
fi

# General aliases
alias c='clear'
alias bitch,=sudo
alias j=jobs

alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../../'

# Git
hub --help > /dev/null 2>&1 && alias git='hub'

# Commiting
alias gp='git push'
complete -o default -o nospace -F _git_push gp

alias gpl='git pull'
complete -o default -o nospace -F _git_pull gpl

alias gd='git diff'
complete -o default -o nospace -F _git_diff gd

alias gc='git commit -v'
alias gca='git commit -av'
alias gcp='git commit -p'

alias gs='git status -sb'

alias gb='git branch -v'
complete -o default -o nospace -F _git_branch gb

alias glog='git log --oneline'
complete -o default -o nospace -F _git_log glog

alias gco='git checkout'
complete -o default -o nospace -F _git_checkout gco

# Ruby
alias be='bundle exec'
alias beer='bundle exec rake'

function rt { 
  bundle exec ruby -Itest $1 #--progress-row-max=8- --user-color=true 
}

alias tmux_to_clip='tmux save-buffer -|pbcopy'
alias tmux_from_clip='tmux set-buffer "$(pbpaste)"'
