#! /bin/bash

alias ls='ls -G'
bind -m vi-insert "\C-l":clear-screen

alias ..='cd ..'
alias ...='cd ../..'

alias gp='git push'
alias gpl='git pull'
alias gd='git diff'
alias gc='git commit -v'
alias gca='git commit -av'
alias gcp='git commit -p'
alias gs='git status -sb'
alias gb='git branch -v'
alias glog='git log --oneline'
alias gco='git checkout'

alias bx='bundle exec'

function rt {
  if [ -e .zeus.sock ]; then
    zeus test $1
  else
    bundle exec ruby -Itest $1
  fi
}

alias tmux_to_clip='tmux save-buffer -|pbcopy'
alias tmux_from_clip='tmux set-buffer "$(pbpaste)"'
