#!/usr/bin/env ruby
require 'colored'

def header(header)
  puts "------> ".blue + "#{header}"
end

def cmd(cmd)
  puts "\t$ #{cmd}".green
  system cmd
end

header "Updating Vim plugins"
cmd "cd ~/.homesick/repos/Sirupsen/dotfiles && git submodule --quiet foreach git pull origin master"

header "Updating Homebrew"
cmd "brew update -s"

header "Upgrading Homebrew"
cmd "brew upgrade -s"

header "Let Homebrew clean up"
cmd "brew cleanup -s"

header "Removing Homebrew cache"
cmd "rm -rf ~/Library/Caches/Homebrew/*"

header "Removing Homebrew orphans"
cmd "brew rm $(join <(brew leaves) <(brew deps $1))"

header "Updating npm"
cmd "npm update npm -g -s"

header "Updating tmux-MacOSX-pasteboard"
cmd "git clone git://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard.git /tmp/pasteboard && cd /tmp/pasteboard"
cmd "make reattach-to-user-namespace && cp reattach-to-user-namespace ~/bin"
cmd "chmod +x ~/.bin/reattach-to-user-namespace"

header "Updating hub"
cmd "curl http://defunkt.io/hub/standalone -sLo ~/.bin/hub && chmod +x ~/.bin/hub"

header "Updating gist"
cmd "curl -s https://raw.github.com/defunkt/gist/master/gist > ~/.bin/gist && chmod +x ~/.bin/gist"

header "Updating vimpager"
cmd "curl -s https://raw.github.com/rkitover/vimpager/master/vimpager > ~/.bin/vimpager && chmox +x ~/.bin/vimpager"

header "Update rbenv.."
cmd "cd ~/.rbenv && git pull"

header "Remove screenshots from desktop"
cmd "rm -rfv ~/Desktop/*Screen\ Shot*.png"


header "Taking out the trash"
cmd "rm -Rf ~/.Trash/*"
