#!/usr/bin/env ruby
# I use this because I forgot to run these commands. Because I even forget to
# run this command, I have the following in my crontab:
#
# 0 * * * * cleanup housework > /dev/null
# 0 18 */3 * * cleanup cleaning > /dev/null

class String
  {
    :red => 31,
    :green => 32,
    :yellow => 33,
    :blue => 34,
    :pink => 35
  }.each do |color, code|
    define_method color do
      "\e[#{code}m#{self}\e[0m"
    end
  end
end

@groups = {}

def header(header)
  puts "------> ".blue + "#{header}.."
end

def cmd(cmd)
  puts "\t$ #{cmd}".green
  system cmd
end

def group(name, &block)
  @groups[name] = block
end

group :upgrade do
  header "Updating Homebrew"
  cmd "brew update -s"

  header "Updating Vim plugins"
  cmd "vim +BundleInstall! +qall"

  header "Upgrading Homebrew"
  cmd "brew upgrade -s"

  header "Updating npm"
  cmd "npm update npm -g -s"

  header "Updating tmux-MacOSX-pasteboard"
  cmd <<-CMD
    rm -rf /tmp/pasteboard && \
    git clone git://github.com/ChrisJohnsen/tmux-MacOSX-pasteboard.git /tmp/pasteboard && \
    cd /tmp/pasteboard && make reattach-to-user-namespace > /dev/null && \
    cp reattach-to-user-namespace ~/bin && \
    chmod +x ~/.bin/reattach-to-user-namespace && rm -rf /tmp/pasteboard
  CMD

  header "Updating hub"
  cmd "curl http://defunkt.io/hub/standalone -sLo ~/.bin/hub && chmod +x ~/.bin/hub"

  header "Updating gist"
  cmd "curl -s https://raw.github.com/defunkt/gist/master/gist > ~/.bin/gist && chmod +x ~/.bin/gist"

  header "Updating vimpager"
  cmd "curl -s https://raw.github.com/rkitover/vimpager/master/vimpager > ~/.bin/vimpager && chmod +x ~/.bin/vimpager"

  header "Update rbenv.."
  cmd "cd ~/.rbenv && git pull"

  header "Update ack"
  cmd "curl -s http://betterthangrep.com/ack-standalone > ~/.bin/ack && chdmox +x ~/.bin/ack"
end


group :cleaning do
  header "Removing Homebrew cache"
  cmd "rm -rf ~/Library/Caches/Homebrew/*"

  header "Removing logs"
  cmd "rm -f ~/Code/**/log/*"

  header "Let Homebrew clean up"
  cmd "brew cleanup -s"

  header "Removing danid.log"
  cmd "rm -f ~/danid.log"

  header "Remove screenshots from desktop"
  cmd "rm -f ~/Desktop/Screen*.png"

  header "Taking out the trash"
  cmd "rm -Rf ~/.Trash/*"
end

group :housework do
  header "Generating ctags"
  cmd "for dir in ~/Code/*; do cd $dir 2> /dev/null; tagz; done"

  header "Index Evernotes"
  cmd "mdimport -r /Applications/Evernote.app/Contents/Library/Spotlight/EvernoteSpotlightImporter.mdimporter"
end

if !ARGV[0] || ARGV[0] == "all"
  @groups.each do |key, value|
    value.call
  end
else
  @groups[ARGV[0].to_sym].call
end

