#!/bin/bash

echo "Updating Vim plugins.."
cd ~/.homesick/repos/Sirupsen/dotfiles
git submodule foreach git pull origin master
cd ~

echo "Updating Homebrew.."
brew update

echo "Upgrading Homebrew.."
brew upgrade

echo "Let Homebrew clean up.."
brew cleanup

echo "Removing Homebrew cache.."
rm -rf ~/Library/Caches/Homebrew/*

echo "Taking out the trash.."
sudo rm -Rf ~/.Trash/*

echo "Update rbenv.."
cd ~/.rbenv
git pull
cd
