#!/usr/bin/env ruby

if File.exists?("Gemfile")
  require 'bundler'

  system("bundle > /dev/null")

  paths = Bundler.load.specs.map(&:full_gem_path)
  system("~/.bin/tagz -f gems.tags #{paths.join(' ')}")
end
