#!/bin/bash
# One liner to upload images to Imgur.
# Note. This is Sirupsen's API key
#
# Author: Sirupsen @ http://sirupsen.dk

curl -s -F "image=@$1" -F "key=486690f872c678126a2c09a9e196ce1b" http://imgur.com/api/upload.xml | grep -E -o "<original_image>(.)*</original_image>" | grep -E -o "http://i.imgur.com/[^<]*"
