#!/usr/bin/env ruby
unless ARGV.empty?
  ARGV.each do |site|
    `echo 127.0.0.1 #{site} www.#{site} >> /etc/hosts.productivity`
  end
  exit
end

if File.exist?("/etc/productive")
  `rm /etc/hosts`
  `cp /etc/hosts.original /etc/hosts`
  `rm /etc/productive`

  puts "Productivity: Deactivated"
else
  `rm /etc/hosts`
  `cp /etc/hosts.productivity /etc/hosts`
  `touch /etc/productive`
  `rvmsudo start_working.ru -p 80`

  puts "Productivity: Activated"
end
