#!/usr/bin/env ruby
require 'csv'

unless ARGV[0]
  puts <<-EOS
Pass the Skype username of the person you want the logs for.

  sskype sirupsen

Then use standard Unix utilities such as `grep`, `cut`, `wc` and `sed` with the
tab seperated output.

Find that hotel Sirupsen talked about the other day:

  sskype sirupsen | grep hotel | tail -n 10

Number of times Ruby has been mentioned in a conversation with Sirupsen:

  sskype sirupsen | grep ruby | wc -l

Number of times Sirupsen has mentioned walruses in a conversation with you:

  sskype | grep -i sirupsen | grep walrus | wc -l
EOS
  exit 1
end

PATH = File.expand_path("~/Library/Application\ Support/Skype/sirupsen")

# Avoid locking the main DB
system "cp \"#{PATH}/main.db\" \"#{PATH}/history.db\""

matches = `sqlite3 -csv "#{PATH}/history.db" "SELECT body_xml,dialog_partner,author,timestamp FROM messages WHERE dialog_partner='#{ARGV[0]}'"`

begin
  CSV.parse(matches) do |(body, _, author, timestamp)|
    puts "#{author}\t#{Time.at(timestamp.to_i)}\t#{body.inspect}"
  end
rescue Errno::EPIPE
  # This will happen if piped to something like head that'll quit after -n lines
end
