#!/usr/bin/env bash
function notify() {
  echo $1
  osascript -e "display notification \"$1\" with title \"Subscriptions\""
}

function mycurl() {
  if [[ $VERBOSE ]]; then
    echo "$@" >&2
  fi

  curl -H "User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_3) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/44.0.2403.89 Safari/537.36" --max-time 5 --retry 10 --silent $@ 2> /dev/null
}

PATH=/usr/local/bin:$PATH

mycurl 'https://www.trailheadpaddleshack.ca/trailhead-canoes-prospector-16-fiberglass.html?id=33830503#' \
  | pup '.out-of-stock' > /dev/null || notify "Canoe Available"

mycurl 'https://www.altitude-sports.com/products/patagonia-nano-air-pants-mens-llll-pat-85100.json' \
  | jq --exit-status ".product.variants | .[] | select(.option2 == \"M\").inventory_quantity > 0" > /dev/null && \
  notify "Nano Air Pants Men in Stock @ Altitude"

mycurl 'https://www.altitude-sports.com/products/patagonia-nano-air-jacket-mens-llll-pat-84252.json' \
  | jq --exit-status ".product.variants | .[] | select(.option2 == \"M\").inventory_quantity > 0" > /dev/null && \
  notify "Nano Air Jacket Men in Stock @ Altitude"

mycurl 'https://www.patagonia.ca/product/mens-nano-air-pants/85100.html' \
  | pup 'a[data-size=M]' | grep -q 'disabled' || \
  notify "Nano Air Pants in Stock @ Patagonia (get hoodie too)"

mycurl 'https://www.altitude-sports.com/products/arcteryx-mens-gamma-ar-pant-llll-arc-17225.json' \
  | jq --exit-status ".product.variants | .[] | select(.option2 == \"M\").inventory_quantity > 0" > /dev/null && \
  notify "Nano Air Pants Men in Stock @ Altitude"

mycurl 'https://www.roguecanada.ca/rogue-dumbbell-bumpers' | \
  pup '.product-purchase-wrapper-50085 .bin-out-of-stock' | \
  grep -q "Notify Me" || notify "Rogue Dumbbell in Stock"

mycurl 'https://www.roguecanada.ca/rogue-color-echo-bumper-plate' | \
  pup '.product-purchase-wrapper-45192 .bin-out-of-stock' | \
  grep -q "Notify Me" || notify "Rogue Echo"

mycurl 'https://www.roguecanada.ca/rogue-hg-2-0-bumper-plates' | \
  pup '.product-purchase-wrapper-22902 .bin-out-of-stock' | \
  grep -q "Notify Me" || notify "Rogue HG 2"

# Get the hoodie too: https://www.patagonia.ca/product/mens-nano-air-hoody/84366.html?dwvar_84366_color=HTE

# ========= GRAVEYARD ============

# mycurl 'https://www.staples.ca/products/2978106-en-hp-colour-laserjet-pro-m255dw-printer'

# mycurl 'https://provinceofcanada.com/products/weekend-hoodie-washed-olive-unisex.json?variant=32653375373389' \
#   | jq --exit-status ".product.variants | .[] | select(.title == \"S\").inventory_quantity > 0" > /dev/null && \
#   notify "Province of Canada Sweater for Jenn"

# mycurl 'https://finerfitness.ca/collections/weight-plates-dumbbells/products/york-rubber-training-bumper-plate?variant=33148913647660' \
#   | pup 'option[value="33148913647660"]' | grep -q "Sold out" || notify "York 15LB at Finer Fitness"

# mycurl 'https://www.roguecanada.ca/rogue-lb-change-plates' | \
#    rg -q 'bin-button-24534' || \
#    notify "Rogue Change Plates"

# mycurl 'https://www.roguecanada.ca/rogue-color-echo-bumper-plate' | \
#    rg -q 'bin-button-65856' || \
#    notify "Rogue Echo Bumper Plates"

# mycurl 'https://www.roguecanada.ca/rogue-hg-2-0-bumper-plates' | \
#    rg -q 'bin-button-22903' || \
#    notify "Rogue HG Bumper Plates"

# mycurl 'https://www.roguecanada.ca/rogue-echo-bumper-plates-with-white-text' | \
#    rg -q 'bin-button-65858' || \
#    notify "Rogue Echo Bumper Plates"

# mycurl 'https://www.roguefitness.com/rogue-color-lb-training-2-0-plates' | \
#    rg -q 'bin-button-23934' || \
#    notify "Rogue Training Plates 25LB"

# mycurl 'https://fitnessavenue.ca/15lb-bumper-weight-plates-2-inch' | \
#    rg -q 'Backordered' || \
#    notify "Amstaff Plates"

# if [[ $(mycurl -s https://gorilafitness.ca/en/york-barbell-solid-rubber-bumper-plates | pup '.unavailable' -n) -lt 2 ]]; then 
#   notify "York Barbells Back in stock at Gorilla"
# fi

# curl --retry 10 -s https://www.roguecanada.ca/black-concept-2-model-d-rower-pm5 | \
#   grep -q 'bin-out-of-stock-cart' || \
#   notify "Rogue Concept-D in Stock"

# curl --retry 10 -s https://fitnessnutrition.ca/products/concept2-modele-d | \
#   grep -q "pt-label-out-stock" || \
#   notify "Fitness Nutrition Concept-D in Stock"

# curl --retry 10 -s https://gorilafitness.ca/en/endurance/concept-2-rower-1510 | \
#   grep -q "stock unavailable" || \
#   notify "Gorilla Fitness Concept-D in Stock"

# curl --retry 10 -s https://www.flamanfitness.com/concept-2-model-d-rower.html | \
#   grep -q "Contact For Price" || \
#   notify "Flaman Fitness Concept-D in Stock"

# curl --retry 10 -s https://www.flamanfitness.com/concept-2-rower-model-e.html | \
#   grep -q "Contact For Price" || \
#   notify "Flaman Fitness Concept-E in Stock"

# curl --retry 10 -s https://iheartsynergee.ca/collections/rowers/products/concept2-model-d | \
#   grep -q "sold_out" || \
#   notify "I Heart Synergee Concept-D in Stock"

# curl --retry 10 -s https://iheartsynergee.ca/collections/rowers/products/concept2-model-e |
#   grep -q "sold_out" || \
#   notify "I Heart Synergee Concept-D in Stock"

# mycurl 'https://vpo.ca/product/323688/nano-air-pants-mens' \
#    rg 'productJson' | rg -o "\{.*\}" | \
#    jq --exit-status ".ProductVariants | .[] | select(.Size | match(\"XL.+\"))" > /dev/null && \
#    notify "Nano Air Pants in Stock @ VPO"

