#!/bin/bash

file="/etc/hosts"
host_access_file="/usr/local/etc/host_access"
today=$(date "+%d/%m/%y")
max_unlocks=3

if [[ $UID != 0 ]]; then
  echo -e "\x1b[31mMust run as root to acccess /etc/hosts"
  exit 1
fi

touch $host_access_file

is_unlocked() {
  grep -q "# 127.0.0.1" $file
}

lock() {
  sed -i '' "s/# 127.0.0.1/127.0.0.1/" $file
  echo -e "\x1b[31mLocked"
}

unlock() {
  local unlocks_today=`grep -c $today $host_access_file`

  if [[ $unlocks_today -ge $max_unlocks ]]; then
    echo -e "\x1b[31mToo many unlocks today: $unlocks_today/$max_unlocks\x1b[33m"
    exit 1
  fi

  echo $today >> $host_access_file
  sed -i '' "s/127.0.0.1/# 127.0.0.1/" $file
  sed -i '' "s/# 127.0.0.1 localhost/127.0.0.1 localhost/" $file
  echo -e "\x1b[32mUnlocked\x1b[33m"

  read -p "Press return to lock"
  lock
}

trap lock SIGINT SIGTERM SIGHUP

if is_unlocked; then
  lock
else
  unlock
fi
