#!/usr/bin/env ruby

require 'rb-fsevent'
require 'rest_client'
require 'json'
require 'fileutils'
require 'pry'

home = File.expand_path("~")

DESKTOP = "#{home}/Desktop"
DUMMY = "#{home}/.bin/last_screenshot_dummy"
API_KEY = "486690f872c678126a2c09a9e196ce1b"

def imgur(file_path)
  url = "http://imgur.com/api/upload.json"
  data = {
    :key => API_KEY, :image => File.open(File.expand_path(file_path))
  }

  response = RestClient.post(url, data)
  JSON.parse(response.body)["rsp"]["image"]["original_image"] rescue nil
end

def touch_dummy(time)
  `touch -t #{time.strftime("%y%m%d%H%M.%S")} #{DUMMY}`
end

def new_file_name
  `find #{DESKTOP} -newer #{DUMMY}`
end

touch_dummy(Time.now)

def image?(file_name)
  file_name.match(/(jpg|png|bmp)$/)
end

fsevent = FSEvent.new
fsevent.watch DESKTOP do |directories|
  images = new_file_name.split("\n").select { |f| image?(f) }

  images.each do |image|
    puts "Uploading #{image}.."
    url = imgur(image)
    puts "Path #{url}"
    system "echo \"#{url} | pbcopy"
    system "rm #{image}"
  end

  touch_dummy(Time.now)
end

fsevent.run
