#!/usr/bin/env ruby
require 'optitron'

class Runner < Optitron::CLI
  desc "Adds a Vim bundle."
  arg_types :string, :string
  def add(url, name)
    puts url
    `git submodule add #{url} ~/.vim/bundle/#{name}`
  end
end
Runner.dispatch
