#! /usr/bin/env ruby

words = File.read(File.expand_path(File.dirname(__FILE__) + '/word.txt')).split("\n")

words = words.select { |w| w.length < 7 }.map { |s| s[0..-2] }

5.times do
  puts words.shuffle[0..2].join("-") + "-" + rand(100).to_s
end

5.times do
  puts words.shuffle[0..2].join(" ") + " " + rand(100).to_s
end
